#!/bin/bash
motion=$(dirname "$0")/motion
eval $($motion --shell "$@")
$motion --format rawvideo -o /dev/stdout "$@" | ffplay -loglevel quiet -f rawvideo -pixel_format $csp -video_size "$w"x"$h" -framerate $fps_num/$fps_den -